# Generated by Django 3.2.13 on 2022-04-27 23:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1024)),
                ('description', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('date_published', models.DateField(default=datetime.date(2022, 4, 27))),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.boardmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1024)),
                ('date_published', models.DateField(default=datetime.date(2022, 4, 27))),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.threadmodel')),
            ],
        ),
    ]
