# Generated by Django 3.2.13 on 2022-04-30 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='link',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 4, 30)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 4, 30)),
        ),
    ]
