# Generated by Django 3.2.13 on 2022-05-01 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20220430_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='board',
            new_name='thread',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
        migrations.AlterField(
            model_name='threadmodel',
            name='date_published',
            field=models.DateField(default=datetime.date(2022, 5, 1)),
        ),
    ]
